### ISSUE TITLE
Can you do this in react?

### ISSUE THREAD

**Issue by swadhinroutray** [fredyhuertas/spacetrash.live#3]
Can you do this in React? is it possible to get a guide to recreate this in a JS framework, preferably React?

**Comment by miguelhuertas** [comment]
@swadhinroutray All the logic is in JS so I imagine there are no problems with passing it to other frameworks.

**Comment by miguelhuertas** [comment]
I forgot:
https://github.com/fredyhuertas/spacetrash.live/blob/main/src/pub/index.html#L141

**Comment by miguelhuertas** [comment]
@swadhinroutray 
https://github.com/fredyhuertas/spacetrash.live/blob/main/src/pub/index.html#L141
